<header>
<form class="deslogado">
<fieldset id="login" class="logado">
<label>login</label> <input type="text" size="15" name="login"><br>
<label>senha</label> <input type="password" size="15" name="senha"><br>
<button>OK</button>
</fieldset>

<fieldset id="login">
<p><a href="settings.php">Settings</a> | <a href="/">Deslogar</a></p>
</fieldset>

<h1><a href="/"><img src="imagens/marca_kidu.gif" width="111" height="40" alt="Kidu"></a></h1>
<fieldset>
<label>busca</label><br><input type="text" size="14" name="buscar"><input type="image" src="imagens/lupa.png" width="23" height="24">
</fieldset>
<br class="tudo">
</form>
</header>